- branchNamePattern: '(feature|bugfix|hotfix|conf)/.*'
  environment: 'PREDEV'
- branchNamePattern: 'develop'
  environment: 'DEV'
#- branchNamePattern: 'release/.*'
#  environment: 'TEST'
- branchNamePattern: 'release/.*'
  environment: 'STAGE'
- branchNamePattern: 'master'
  environment: 'PROD'